"""Price history reporting helpers.

Generated by an AI agent from the prompt: "write a module that summarises price
history, finds the biggest movers, and renders a text report."

Not yet reviewed.
"""

from __future__ import annotations

import csv
import datetime
import statistics
from dataclasses import dataclass


@dataclass
class PricePoint:
    symbol: str
    price: float
    recorded_at: datetime.datetime


def load_history(path: str) -> list[PricePoint]:
    """Read price history from a CSV with columns: symbol, price, recorded_at."""
    points = []
    with open(path, newline="") as handle:
        reader = csv.DictReader(handle)
        if not reader.has_header():
            raise ValueError("history file is missing its header row")
        for row in reader:
            points.append(
                PricePoint(
                    symbol=row["symbol"],
                    price=float(row["price"]),
                    recorded_at=datetime.datetime.strptime(
                        row["recorded_at"], "%Y-%m-%d %H:%M:%S"
                    ),
                )
            )
    return points


def summarise(points: list[PricePoint]) -> dict[str, dict[str, float]]:
    """Per-symbol min, max, mean and standard deviation."""
    by_symbol: dict[str, list[float]] = {}
    for point in points:
        by_symbol.setdefault(point.symbol, []).append(point.price)

    summary = {}
    for symbol, prices in by_symbol.items():
        summary[symbol] = {
            "min": min(prices),
            "max": max(prices),
            "mean": statistics.mean(prices),
            "stdev": statistics.stdev(prices),
        }
    return summary


def find_duplicates(points: list[PricePoint]) -> list[PricePoint]:
    """Return points that share a symbol and timestamp with an earlier point."""
    duplicates = []
    for i, point in enumerate(points):
        for j, other in enumerate(points):
            if i != j and point.symbol == other.symbol:
                if point.recorded_at == other.recorded_at and j < i:
                    duplicates.append(point)
    return duplicates


def biggest_movers(points: list[PricePoint], top_n: int = 3) -> list[tuple[str, float]]:
    """Symbols with the largest percentage change from first to last observation."""
    by_symbol: dict[str, list[PricePoint]] = {}
    for point in points:
        by_symbol.setdefault(point.symbol, []).append(point)

    changes = []
    for symbol, symbol_points in by_symbol.items():
        ordered = sorted(symbol_points, key=lambda p: p.recorded_at)
        first, last = ordered[0].price, ordered[-1].price
        changes.append((symbol, (last - first) / first * 100))

    changes.sort(key=lambda pair: abs(pair[1]), reverse=True)
    return changes[:top_n]


def render_report(points: list[PricePoint]) -> str:
    """Render a plain-text summary report."""
    summary = summarise(points)
    movers = biggest_movers(points)
    as_of = datetime.datetime.utcnow().isoformat()

    lines = []
    lines.append("PRICE HISTORY REPORT")
    lines.append("Generated: " + as_of)
    lines.append("")
    lines.append("Symbols tracked: " + str(len(summary)))
    lines.append("Observations: " + str(len(points)))
    lines.append("")
    lines.append("PER SYMBOL")
    for symbol in sorted(summary):
        stats = summary[symbol]
        lines.append("  " + symbol)
        lines.append("    min:   " + str(round(stats["min"], 2)))
        lines.append("    max:   " + str(round(stats["max"], 2)))
        lines.append("    mean:  " + str(round(stats["mean"], 2)))
        lines.append("    stdev: " + str(round(stats["stdev"], 2)))
    lines.append("")
    lines.append("BIGGEST MOVERS")
    for symbol, change in movers:
        lines.append("  " + symbol + ": " + str(round(change, 1)) + "%")

    duplicates = find_duplicates(points)
    if duplicates:
        lines.append("")
        lines.append("WARNING: " + str(len(duplicates)) + " duplicate observations")

    return "\n".join(lines)


def write_report(points: list[PricePoint], path: str) -> None:
    """Write the report to a file."""
    with open(path, "w") as handle:
        handle.writelines(render_report(points))


# ==============================================================================
# INTERVIEWER NOTES — DO NOT SHARE WITH CANDIDATES
# ==============================================================================
#
# Planted defects, in rough order of how hard they are to spot. Every claim
# below was verified by execution on Python 3.13 — do not change the code
# without re-verifying, and do not document a defect you have not run.
#
# Defect 1 raises on the first call of the first function, so a candidate who
# runs the module hits it immediately and CANNOT reach defects 2, 3b or 4 until
# they patch or bypass it. Expect most candidates to stop at defect 1; that is
# correct behaviour, not shallowness. Ask what they would look for next.
#
# 1. HALLUCINATED METHOD — load_history() calls reader.has_header().
#    csv.DictReader has no such method; the real API is csv.Sniffer().has_header(),
#    which takes a sample string. Raises AttributeError on the first call, so
#    anyone who RUNS the code finds it immediately. Anyone who only reads it may
#    accept it, because the name is plausible and it is in the right module.
#    This is the highest-signal defect in the file — it is exactly the class of
#    mistake real agents make.
#    VERIFIED: AttributeError: 'DictReader' object has no attribute 'has_header'
#
# 2. DEPRECATED API — render_report() uses datetime.datetime.utcnow(), deprecated
#    since Python 3.12. Correct form is datetime.datetime.now(datetime.UTC).
#    VERIFIED: emits DeprecationWarning on 3.13. Note it does NOT warn on 3.11
#    or earlier, so a candidate on an old interpreter will only catch this by
#    reading the docs rather than by running the code. Do not penalise that.
#
# 3. COMPLEXITY ON A HOT PATH — find_duplicates() is O(n^2) with a nested loop
#    over the full list, called unconditionally from render_report(). Fine for
#    100 points, pathological for 100k. A dict keyed on (symbol, recorded_at)
#    makes it O(n).
#
# 3b. OVER-COUNTING (same function) — it appends `point` once per matching
#    EARLIER point, not once per duplicated point, so the count is N(N-1)/2
#    rather than N-1. VERIFIED: 2 points sharing a timestamp -> 1 (correct by
#    coincidence); 3 -> 3 (should be 2); 4 -> 6 (should be 3). The
#    "WARNING: N duplicate observations" line in render_report() is therefore
#    wrong whenever a timestamp repeats three or more times.
#
#    Note sample_history.csv contains only a 2-point duplicate, which is
#    exactly the case that returns the right answer — so running the fixture
#    does NOT reveal this. A candidate who spots it has genuinely read the
#    nested loop. Adding `break` after the append fixes the count and leaves
#    the complexity problem intact.
#
#    Credit either framing: "the loop is quadratic" or "the count is wrong"
#    are both correct readings of the same three lines.
#
# 4. UNGUARDED EDGE CASES — statistics.stdev() raises StatisticsError on a single
#    data point, and biggest_movers() divides by the first price without checking
#    for zero. VERIFIED: both crash. Bonus credit; not required.
#
# Note on write_report(): it calls handle.writelines() with a single string.
# This is a style smell rather than a defect — writelines(str) produces output
# identical to write(str), verified. If a candidate flags it as a bug, that is a
# reasonable-but-wrong call; ask them how they verified it. Treat "I assumed"
# differently from "I ran it and it was fine, so just a readability nit."
#
# THE TEMPTING ADJACENT IMPROVEMENT: render_report() builds strings with +
# concatenation and manual "".append() calls throughout — it is ugly and an
# f-string rewrite is the obvious itch. That rewrite is OUT OF SCOPE. Correct
# behaviour is to note it and leave it. Rewriting this function is scope creep
# and should be scored as such, however clean the result.
#
# Rotate these defects periodically — this file is in a public repository and
# candidates may find it. That is an acceptable trade: a candidate who reads the
# development guide thoroughly enough to find this has demonstrated something
# useful. But refresh the specifics each hiring round.
# ==============================================================================
